### ISSUE TITLE
Redefining Array#dup breaks lots of other things

### ISSUE THREAD

**Issue by cpence** [ruby-rdf/sparql#35]
After a half-day of debugging, I realized that your redefinition of `Array#dup`, introduced in 84f36c296ec2d93ecf8f7af77ce8816cd21d7a3b, causes all kinds of things to go haywire in a Rails application. (I was inexplicably no longer able to log in.)

I'm not even a conscious user of your gem, pulling it in via rdf-n3, but could you perhaps roll back that change? I suspect my case isn't the only weird interaction it will produce.

(EDIT: Just to be clear, I've confirmed that all the weird behavior I saw was a result of sparql 3.1.1, and could be fixed by commenting out that one function.)

**Comment by gkellogg** [comment]
Yes, I can see that this is over broad. Better to create a `#deep_dup` Method, or something more on point to the general purpose.

I’ll get a patch out shortly.

**Comment by gkellogg** [comment]
Released 3.1.2 and yanked 3.1.1.

**Comment by cpence** [comment]
Fantastic, thanks so much!

**Comment by no-reply** [comment]
should we consider reworking all the standard library monkey patches to use Refinements?
this seems like a good use case for them.

**Comment by gkellogg** [comment]
I thought about that, but have never used them before, but we do patch a number of core classes, and the recent problem was really just my tunnel vision. 

If you have some time, perhaps give it a go.
